/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2016-04-04 00:05:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.servlet.http.HttpSession;
import com.ktds.pingpong.member.vo.MemberVO;

public final class MemberInformation_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1459327742000L));
    _jspx_dependants.put("jar:file:/C:/Users/206-001/workspace/JSP_WEB/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Project-Front/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1090214156000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("javax.servlet.http.HttpSession");
    _jspx_imports_classes.add("com.ktds.pingpong.member.vo.MemberVO");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"utf-8\">\r\n");
      out.write("        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("        <title>PingPong Chat</title>\r\n");
      out.write("        <!-- Vendor CSS -->\r\n");
      out.write("        <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/vendors/animate-css/animate.min.css\" rel=\"stylesheet\">\r\n");
      out.write("        <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/vendors/bootgrid/jquery.bootgrid.min.css\" rel=\"stylesheet\">\r\n");
      out.write("        <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/vendors/fullcalendar/fullcalendar.css\" rel=\"stylesheet\">\r\n");
      out.write("        <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/vendors/sweet-alert/sweet-alert.min.css\" rel=\"stylesheet\">\r\n");
      out.write("        <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/vendors/light-gallery/lightGallery.min.css\" rel=\"stylesheet\">\r\n");
      out.write("        <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/vendors/material-icons/material-design-iconic-font.min.css\" rel=\"stylesheet\">\r\n");
      out.write("        <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/vendors/socicon/socicon.min.css\" rel=\"stylesheet\">\r\n");
      out.write("            \r\n");
      out.write("        <!-- CSS -->\r\n");
      out.write("        <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/css/app.min.1.css\" rel=\"stylesheet\">\r\n");
      out.write("        <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/css/app.min.2.css\" rel=\"stylesheet\">\r\n");
      out.write("        <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/css/display.property.css\" rel=\"stylesheet\">\r\n");
      out.write("        <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/css/profile.css\" rel=\"stylesheet\">\r\n");
      out.write("   \t    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/vendors/light-gallery/hovereffect.css\" rel=\"stylesheet\">\r\n");
      out.write("        \r\n");
      out.write("        <!-- Javascript Libraries -->\r\n");
      out.write("        <script src=\"resource/js/jquery-2.1.1.min.js\"></script>\r\n");
      out.write("        <script src=\"resource/js/bootstrap.min.js\"></script>\r\n");
      out.write("        \r\n");
      out.write("        <script src=\"resource/vendors/nicescroll/jquery.nicescroll.min.js\"></script>\r\n");
      out.write("        <script src=\"resource/vendors/auto-size/jquery.autosize.min.js\"></script>\r\n");
      out.write("        <script src=\"resource/vendors/waves/waves.min.js\"></script>\r\n");
      out.write("        <script src=\"resource/vendors/bootgrid/jquery.bootgrid.min.js\"></script>\r\n");
      out.write("        <script src=\"resource/vendors/bootstrap-growl/bootstrap-growl.min.js\"></script>\r\n");
      out.write("        <script src=\"resource/vendors/sweet-alert/sweet-alert.min.js\"></script>\r\n");
      out.write("        <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${root}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resource/resource/vendors/fileinput/fileinput.min.js\"></script>\r\n");
      out.write("        <script src=\"resource/vendors/chosen/chosen.jquery.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"resource/vendors/bootstrap-select/bootstrap-select.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"resource/vendors/bootstrap-wizard/jquery.bootstrap.wizard.min.js\"></script>\r\n");
      out.write("        \r\n");
      out.write("        <script src=\"resource/js/functions.js\"></script>\r\n");
      out.write("        <script src=\"resource/js/demo.js\"></script>\r\n");
      out.write("        \r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready( function() {\r\n");
      out.write("\t\tfunction notify(from, align, icon, type, animIn, animOut){\r\n");
      out.write("\t\t    $.growl({\r\n");
      out.write("\t\t        icon: icon,\r\n");
      out.write("\t\t        title: '',\r\n");
      out.write("\t\t        message: 'Your password is not correct',\r\n");
      out.write("\t\t        url: ''\r\n");
      out.write("\t\t    },{\r\n");
      out.write("\t\t            element: 'body',\r\n");
      out.write("\t\t            type: type,\r\n");
      out.write("\t\t            allow_dismiss: true,\r\n");
      out.write("\t\t            placement: {\r\n");
      out.write("\t\t                    from: from,\r\n");
      out.write("\t\t                    align: align\r\n");
      out.write("\t\t            },\r\n");
      out.write("\t\t            offset: {\r\n");
      out.write("\t\t                x: 20,\r\n");
      out.write("\t\t                y: 85\r\n");
      out.write("\t\t            },\r\n");
      out.write("\t\t            spacing: 10,\r\n");
      out.write("\t\t            z_index: 1031,\r\n");
      out.write("\t\t            delay: 2500,\r\n");
      out.write("\t\t            timer: 1000,\r\n");
      out.write("\t\t            url_target: '_blank',\r\n");
      out.write("\t\t            mouse_over: false,\r\n");
      out.write("\t\t            animate: {\r\n");
      out.write("\t\t                    enter: animIn,\r\n");
      out.write("\t\t                    exit: animOut\r\n");
      out.write("\t\t            },\r\n");
      out.write("\t\t            icon_type: 'class',\r\n");
      out.write("\t\t            template: '<div data-growl=\"container\" class=\"alert\" role=\"alert\">' +\r\n");
      out.write("\t\t                            '<button type=\"button\" class=\"close\" data-growl=\"dismiss\">' +\r\n");
      out.write("\t\t                                '<span aria-hidden=\"true\">&times;</span>' +\r\n");
      out.write("\t\t                                '<span class=\"sr-only\">Close</span>' +\r\n");
      out.write("\t\t                            '</button>' +\r\n");
      out.write("\t\t                            '<span data-growl=\"icon\"></span>' +\r\n");
      out.write("\t\t                            '<span data-growl=\"title\"></span>' +\r\n");
      out.write("\t\t                            '<span data-growl=\"message\"></span>' +\r\n");
      out.write("\t\t                            '<a href=\"#\" data-growl=\"url\"></a>' +\r\n");
      out.write("\t\t                        '</div>'\r\n");
      out.write("\t\t    });\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar jsonData3 = {};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#saveInfo\").click( function(e) {\r\n");
      out.write("\t\t\tvar name = $(\"#name\").val();\r\n");
      out.write("\t\t\tvar afterPw = $(\"#afterPw\").val();\r\n");
      out.write("\t\t\tvar beforePw = $(\"#beforePw\").val();\r\n");
      out.write("\t\t\t$.post(\r\n");
      out.write("\t\t\t\t\t\"/doChangeInfo\"\r\n");
      out.write("\t\t\t\t\t, { \"name\" : name,\r\n");
      out.write("\t\t\t\t\t\t\"afterPw\" : afterPw,\r\n");
      out.write("\t\t\t\t\t\t\"beforePw\" : beforePw }\r\n");
      out.write("\t\t\t\t\t, function(data) {\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\ttry{\r\n");
      out.write("\t\t\t\t\t\t\tjsonData3 = JSON.parse(data);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tcatch(e) { //자바스크립트는 타입이 없기때문에 e만 적으면 된다.\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tif ( jsonData3.isUpdate ) {\r\n");
      out.write("\t\t\t\t\t\t\t location.href=\"/doLogout\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif ( jsonData3.checkPw == false ) {\r\n");
      out.write("\t\t\t\t\t\t    notify('top','center', 'fa fa-comments', 'inverse', 'animated fadeInDown', 'animated fadeOutDown');\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t  }\r\n");
      out.write("\t\t\t\t\t);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#data-table-basic\").bootgrid({\r\n");
      out.write("            css: {\r\n");
      out.write("                icon: 'md icon',\r\n");
      out.write("                iconColumns: 'md-view-module',\r\n");
      out.write("                iconDown: 'md-expand-more',\r\n");
      out.write("                iconRefresh: 'md-refresh',\r\n");
      out.write("                iconUp: 'md-expand-less'\r\n");
      out.write("            },\r\n");
      out.write("        });\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#data-table-command\").bootgrid({\r\n");
      out.write("            css: {\r\n");
      out.write("                icon: 'md icon',\r\n");
      out.write("                iconColumns: 'md-view-module',\r\n");
      out.write("                iconDown: 'md-expand-more',\r\n");
      out.write("                iconRefresh: 'md-refresh',\r\n");
      out.write("                iconUp: 'md-expand-less'\r\n");
      out.write("            }\r\n");
      out.write("            /* formatters: {\r\n");
      out.write("                \"commands\": function(column, row) {\r\n");
      out.write("                    return \"<button type=\\\"submit\\\" class=\\\"btn btn-icon command-delete\\\" data-row-id=\\\"\" + row.id + \"\\\"><span class=\\\"md md-delete\\\"></span></button>\";\r\n");
      out.write("                }\r\n");
      out.write("            } */\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar fileTarget = $('.filebox .upload-hidden');\r\n");
      out.write("\r\n");
      out.write("\t\t  fileTarget.on('change', function(){  // 값이 변경되면\r\n");
      out.write("\t\t    if(window.FileReader){  // modern browser\r\n");
      out.write("\t\t      var filename = $(this)[0].files[0].name;\r\n");
      out.write("\t\t    } \r\n");
      out.write("\t\t    else {  // old IE\r\n");
      out.write("\t\t      var filename = $(this).val().split('/').pop().split('\\\\').pop();  // 파일명만 추출\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t    // 추출한 파일명 삽입\r\n");
      out.write("\t\t    $(this).siblings('.upload-name').val(filename);\r\n");
      out.write("\t\t  });\r\n");
      out.write("\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<style>\r\n");
      out.write("::-webkit-scrollbar {width: 8px; height: 8px; border: 3px solid #fff; }\r\n");
      out.write("::-webkit-scrollbar-button:start:decrement, ::-webkit-scrollbar-button:end:increment {display: block; height: 10px; background: url('./images/bg.png') #efefef}\r\n");
      out.write("::-webkit-scrollbar-track {background: #efefef; -webkit-border-radius: 10px; border-radius:10px; -webkit-box-shadow: inset 0 0 4px rgba(0,0,0,.2)}\r\n");
      out.write("::-webkit-scrollbar-thumb {height: 50px; width: 50px; background: rgba(0,0,0,.2); -webkit-border-radius: 8px; border-radius: 8px; -webkit-box-shadow: inset 0 0 4px rgba(0,0,0,.1)}\r\n");
      out.write("html{scrollbar-3dLight-Color: #efefef; scrollbar-arrow-color: #dfdfdf; scrollbar-base-color: #efefef; scrollbar-Face-Color: #dfdfdf; scrollbar-Track-Color: #efefef; scrollbar-DarkShadow-Color: #efefef; scrollbar-Highlight-Color: #efefef; scrollbar-Shadow-Color: #efefef;}\r\n");
      out.write("#myProgress {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 30px;\r\n");
      out.write("    background-color: white;\r\n");
      out.write("}\r\n");
      out.write("#myBar {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    width: 1%;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    background-color: green;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".filebox input[type=\"file\"] {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    width: 1px;\r\n");
      out.write("    height: 1px;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    margin: -1px;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    clip:rect(0,0,0,0);\r\n");
      out.write("    border: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".filebox label {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    padding: .5em .75em;\r\n");
      out.write("    color: #999;\r\n");
      out.write("    font-size: inherit;\r\n");
      out.write("    line-height: normal;\r\n");
      out.write("    vertical-align: middle;\r\n");
      out.write("    background-color: #fdfdfd;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* named upload */\r\n");
      out.write(".filebox .upload-name {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    padding: .5em .75em;\r\n");
      out.write("    font-size: inherit;\r\n");
      out.write("    font-family: inherit;\r\n");
      out.write("    font-color: black;\r\n");
      out.write("    line-height: normal;\r\n");
      out.write("    vertical-align: middle;\r\n");
      out.write("    background-color: #f5f5f5;\r\n");
      out.write("  border: 1px solid #ebebeb;\r\n");
      out.write("  border-bottom-color: #e2e2e2;\r\n");
      out.write("  border-radius: .25em;\r\n");
      out.write("  -webkit-appearance: none;\r\n");
      out.write("  -moz-appearance: none;\r\n");
      out.write("  appearance: none;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f2(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f3(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f4(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f5(_jspx_page_context))
        return;
      out.write(" \r\n");
      out.write("<body>\r\n");
      out.write("       <header id=\"header\">\r\n");
      out.write("            <ul class=\"header-inner\">\r\n");
      out.write("                <li>\r\n");
      out.write("                    <div class=\"line-wrap\">\r\n");
      out.write("                        <div class=\"line top\"></div>\r\n");
      out.write("                        <div class=\"line center\"></div>\r\n");
      out.write("                        <div class=\"line bottom\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"logo hidden-xs\">\r\n");
      out.write("                    <a class=\"orgin\" href=\"/goMain\">PingPong Chat</a>\r\n");
      out.write("                </li>\r\n");
      out.write("               \t\t \r\n");
      out.write("              <li class=\"pull-right\">\r\n");
      out.write("                <ul class=\"top-menu\">\r\n");
      out.write("                \t<li class=\"logo\" style=\"position: relative; top: 1px;\">\r\n");
      out.write("                    \t<a class=\"my\" href=\"/goMain\">\r\n");
      out.write("                    \t<i class=\"md-timer-auto\" style=\"width: 200%; height: 200%;\"> Welcome ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ Username }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("  ( ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ Useremail }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" ) </i></a>\r\n");
      out.write("                \t</li> \r\n");
      out.write("                    <li class=\"dropdown\">\r\n");
      out.write("                        <a data-toggle=\"dropdown\" class=\"tm-settings\" href=\"\"></a>\r\n");
      out.write("                        <ul class=\"dropdown-menu dm-icon pull-right\">\r\n");
      out.write("                       \t\t<li>\r\n");
      out.write("                            \t<a href=\"/doLogout\"><i class=\"md md-history\"></i> Logout</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a data-action=\"fullscreen\" href=\"\"><i class=\"md md-fullscreen\"></i> Toggle Fullscreen</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"/doAboutProfile\"><i class=\"md md-person\"></i> Privacy Settings</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            \r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </header>\r\n");
      out.write("        \r\n");
      out.write("        <section id=\"main\">\r\n");
      out.write("\t          <section id=\"content\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("\t\t\t\t<div id=\"defaultPage\">\r\n");
      out.write("\t\t\t\t\t <div class=\"block-header\">\r\n");
      out.write("                        <h2>Member Information <small> you can modify your information</small></h2>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"card\" id=\"profile-main\">\r\n");
      out.write("                        <div class=\"pm-overview c-overflow\">\r\n");
      out.write("                            <div class=\"pmo-pic\">\r\n");
      out.write("                                <div class=\"p-relative\">\r\n");
      out.write("                                \t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                    ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#modalProfile\" data-target-color=\"lightblue\" data-toggle=\"modal\" class=\"pmop-edit\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"md md-camera-alt\"></i> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"hidden-xs\">프로필 사진 변경</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("                                <!-- Modal -->\r\n");
      out.write("\t\t                           <div class=\"modal fade\" data-modal-color=\"bluegray\" id=\"modalProfile\" data-backdrop=\"static\" data-keyboard=\"false\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("\t\t                                <div class=\"modal-dialog modal-sm\">\r\n");
      out.write("\t\t                                    <div class=\"modal-content\">\r\n");
      out.write("\t\t                                        <div class=\"modal-header\">\r\n");
      out.write("\t\t                                            <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<h4 class=\"modal-title\">프로필 사진 변경</h4>\r\n");
      out.write("\t\t                                        </div>\r\n");
      out.write("\t\t                                        <form id=\"profileModal\" method=\"post\" action=\"/updatePhoto\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t                                        <div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<p>원하시는 사진을 선택하세요.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"filebox bs3-primary\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input class=\"upload-name\" value=\"파일선택\" disabled=\"disabled\" style=\"color:black;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"btn bgm-bluegray\" for=\"ex_filename\" id=\"isFile\">Select</label> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input id=\"ex_filename\" class=\"upload-hidden\" type=\"file\" name=\"upPhoto\" value=\"file\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t                                       \t</div>\r\n");
      out.write("\t\t\t                                        <div class=\"modal-footer\">\r\n");
      out.write("\t\t\t                                            <button class=\"btn btn-link\" type=\"submit\" >Save</button>\r\n");
      out.write("\t\t\t                                            <button type=\"button\" class=\"btn btn-link\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("\t\t\t                                        </div>\r\n");
      out.write("\t\t                                        </form>\r\n");
      out.write("\t\t                                    </div>\r\n");
      out.write("\t\t                                </div>\r\n");
      out.write("\t\t                            </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("                                \r\n");
      out.write("                                <div class=\"pmo-stat\">\r\n");
      out.write("                                    <h2 class=\"m-0 c-white\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ Username }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h2>\r\n");
      out.write("                                    ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ Useremail }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- <div class=\"pmo-block pmo-contact hidden-xs\">\r\n");
      out.write("                                <h2>Team Information</h2>\r\n");
      out.write("                                \r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li><i class=\"md md-phone\"></i> 00971 12345678 9</li>\r\n");
      out.write("                                    <li><i class=\"md md-email\"></i> malinda-h@gmail.com</li>\r\n");
      out.write("                                    <li><i class=\"socicon socicon-skype\"></i> malinda.hollaway</li>\r\n");
      out.write("                                    <li><i class=\"socicon socicon-twitter\"></i> @malinda (twitter.com/malinda)</li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <i class=\"md md-location-on\"></i>\r\n");
      out.write("                                        <address class=\"m-b-0\">\r\n");
      out.write("                                            10098 ABC Towers, <br/>\r\n");
      out.write("                                            Dubai Silicon Oasis, Dubai, <br/>\r\n");
      out.write("                                            United Arab Emirates\r\n");
      out.write("                                        </address>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>-->\r\n");
      out.write("                        </div> \r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"pm-body clearfix\">\r\n");
      out.write("                            <ul class=\"tab-nav\" role=\"tablist\" data-tab-color=\"amber\">\r\n");
      out.write("                                <li class=\"active\"><a href=\"#teamInfo\" aria-controls=\"teamInfo\" role=\"tab\" data-toggle=\"tab\">Team Information</a></li>\r\n");
      out.write("                                <li><a href=\"#changeInfo\" aria-controls=\"changeInfo\" role=\"tab\" data-toggle=\"tab\">Change Information</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                            \r\n");
      out.write("                            <div class=\"tab-content\">\r\n");
      out.write("\t\t\t\t\t\t    \t\r\n");
      out.write("\t\t\t\t\t\t    \t\r\n");
      out.write("\t\t\t\t\t\t    \t<!-- Team Info -->\r\n");
      out.write("\t\t\t\t\t\t    \t<div role=\"tabpanel\" class=\"tab-pane active\" id=\"teamInfo\">\r\n");
      out.write("\t\t\t\t\t\t\t        <div class=\"pmb-block\">\r\n");
      out.write("\t\t                                <div class=\"pmbb-header\">\r\n");
      out.write("\t\t                                    <h2><i class=\"md md-equalizer m-r-5\"></i> Team List</h2>\r\n");
      out.write("\t                                \t</div>\r\n");
      out.write("\t                                <div class=\"pmbb-body p-l-30\">\r\n");
      out.write("\t                                    <div class=\"pmbb-view\">\r\n");
      out.write("\t                                        <div class=\"panel-group\" role=\"tablist\" data-collapse-color=\"amber\" aria-multiselectable=\"true\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t    <div class=\"panel panel-collapse\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t        <div class=\"panel-heading\" role=\"tab\" id=\"headingOne\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t            <h4 class=\"panel-title\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t                <a data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#collapseOne\" aria-expanded=\"true\" aria-controls=\"collapseOne\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t                  Team List\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t              </a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t          </h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t      <div id=\"collapseOne\" class=\"collapse in\" role=\"tabpanel\" aria-labelledby=\"headingOne\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t          <div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t           </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t       </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t   </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t                                    </div>\r\n");
      out.write("\t                                </div>\r\n");
      out.write("                            \t\t</div>\r\n");
      out.write("\t                            \t<div class=\"pmb-block\">\r\n");
      out.write("\t                                <div class=\"pmbb-header\">\r\n");
      out.write("\t                                    <h2><i class=\"md md-person m-r-5\"></i> Basic Information</h2>\r\n");
      out.write("\t                                </div>\r\n");
      out.write("\t                                <div class=\"pmbb-body p-l-30\">\r\n");
      out.write("\t                                    <div class=\"pmbb-view\">\r\n");
      out.write("\t                                        <dl class=\"dl-horizontal\">\r\n");
      out.write("\t                                            <dt>name</dt>\r\n");
      out.write("\t                                            <dd>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ Username }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</dd>\r\n");
      out.write("\t                                        </dl>\r\n");
      out.write("\t                                        <dl class=\"dl-horizontal\">\r\n");
      out.write("\t                                            <dt>email</dt>\r\n");
      out.write("\t                                            <dd>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ Useremail }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</dd>\r\n");
      out.write("\t                                        </dl>\r\n");
      out.write("\t                                    </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\t                            \t</div>\r\n");
      out.write("                            \t</div>\r\n");
      out.write("\t          \t\t\t\t\r\n");
      out.write("\t          \t\t\t\t\t<!-- change Info -->\r\n");
      out.write("\t\t\t\t\t\t    \t<div role=\"tabpanel\" class=\"tab-pane\" id=\"changeInfo\">\r\n");
      out.write("\t\t                            \t<div class=\"pmb-block\">\r\n");
      out.write("\t\t\t                                <div class=\"pmbb-header\">\r\n");
      out.write("\t\t\t                                    <h2><i class=\"md md-person m-r-5\"></i> Change Information</h2>\r\n");
      out.write("\t\t\t                                    <ul class=\"actions\">\r\n");
      out.write("\t\t\t                                        <li class=\"dropdown\">\r\n");
      out.write("\t\t\t                                            <a href=\"\" data-toggle=\"dropdown\">\r\n");
      out.write("\t\t\t                                                <i class=\"md md-more-vert\"></i>\r\n");
      out.write("\t\t\t                                            </a>\r\n");
      out.write("\t\t\t                                            \r\n");
      out.write("\t\t\t                                            <ul class=\"dropdown-menu dropdown-menu-right\">\r\n");
      out.write("\t\t\t                                                <li>\r\n");
      out.write("\t\t\t                                                    <a data-pmb-action=\"edit\" href=\"\">Edit</a>\r\n");
      out.write("\t\t\t                                                </li>\r\n");
      out.write("\t\t\t                                            </ul>\r\n");
      out.write("\t\t\t                                        </li>\r\n");
      out.write("\t\t                                    \t</ul>\r\n");
      out.write("\t\t                               \t\t</div>\r\n");
      out.write("\t\t\t                                <div class=\"pmbb-body p-l-30\">\r\n");
      out.write("\t\t\t                                    <div class=\"pmbb-view\">\r\n");
      out.write("\t\t\t                                        <dl class=\"dl-horizontal\">\r\n");
      out.write("\t\t\t                                            <dt>name</dt>\r\n");
      out.write("\t\t\t                                            <dd>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ Username }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</dd>\r\n");
      out.write("\t\t\t                                        </dl>\r\n");
      out.write("\t\t\t                                        <dl class=\"dl-horizontal\">\r\n");
      out.write("\t\t\t                                            <dt>email</dt>\r\n");
      out.write("\t\t\t                                            <dd>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ Useremail }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</dd>\r\n");
      out.write("\t\t\t                                        </dl>\r\n");
      out.write("\t\t                                    \t</div>\r\n");
      out.write("\t\t                                    \r\n");
      out.write("\t\t                                    <div class=\"pmbb-edit\">\r\n");
      out.write("\t\t                                        <dl class=\"dl-horizontal\">\r\n");
      out.write("\t\t                                            <dt class=\"p-t-10\">User name</dt>\r\n");
      out.write("\t\t                                            <dd>\r\n");
      out.write("\t\t                                                <div class=\"fg-line\">\r\n");
      out.write("\t\t                                                    <input type=\"text\" id=\"name\" name=\"name\" class=\"form-control\" placeholder=\"eg. ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ Username }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t                                                </div>\r\n");
      out.write("\t\t                                            </dd>\r\n");
      out.write("\t\t                                        </dl>\r\n");
      out.write("\t\t                                        <dl class=\"dl-horizontal\">\r\n");
      out.write("\t\t\t                                            <dt>User email</dt>\r\n");
      out.write("\t\t\t                                            <dd>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ Useremail }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</dd>\r\n");
      out.write("\t\t                                        </dl>\r\n");
      out.write("\t\t                                        <dl class=\"dl-horizontal\">\r\n");
      out.write("\t\t                                            <dt class=\"p-t-10\">Password</dt>\r\n");
      out.write("\t\t                                            <dd>\r\n");
      out.write("\t\t                                                <div class=\"fg-line\">\r\n");
      out.write("\t\t                                                    <input type=\"password\" id=\"beforePw\" name=\"beforePw\" class=\"form-control\" placeholder=\"before password\">\r\n");
      out.write("\t\t                                                </div>\r\n");
      out.write("\t\t                                                <div class=\"fg-line\">\r\n");
      out.write("\t\t                                                    <input type=\"password\" id=\"afterPw\" name=\"afterPw\" class=\"form-control\" placeholder=\"after password\">\r\n");
      out.write("\t\t                                                </div>\r\n");
      out.write("\t\t                                                \r\n");
      out.write("\t\t                                            </dd>\r\n");
      out.write("\t\t                                        </dl>\r\n");
      out.write("\t\t                                        \r\n");
      out.write("\t\t                                        <dl class = \"dl-horizontal\">\r\n");
      out.write("\t\t                                        \tPlease login again.\r\n");
      out.write("\t\t                                        </dl>\r\n");
      out.write("\t\t                                        <div class=\"m-t-30\">\r\n");
      out.write("\t\t                                            <button class=\"btn btn-primary btn-sm\" id=\"saveInfo\" >Save</button>\r\n");
      out.write("\t\t                                            <button data-pmb-action=\"reset\" class=\"btn btn-link btn-sm\">Cancel</button>\r\n");
      out.write("\t\t                                        </div>\r\n");
      out.write("\t\t                                    </div>\r\n");
      out.write("\t\t                            \t</div>\r\n");
      out.write("\t                            \t</div>\r\n");
      out.write("\t\t          \t\t\t\t</div><!-- changeInfo -->\r\n");
      out.write("\t          \t\t\t\t\r\n");
      out.write("\t          \t\t\t\t\r\n");
      out.write("\t          \t\t\t\t\r\n");
      out.write("\t          \t\t\t\t\r\n");
      out.write("\t          \t\t\t\t\t");
      out.write("\r\n");
      out.write("                            \t\t\r\n");
      out.write("                            \t");
      out.write("\r\n");
      out.write("                            \t\t\r\n");
      out.write("                            \t\t\r\n");
      out.write("                            \t</div><!-- tab content -->\r\n");
      out.write("                            \t\t<!-- <div class=\"modal\" id=\"manage\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                <div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                     <div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                         <h4 class=\"modal-title\" align=\"center\">Manage Team</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                     </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                        <form id=\"manage\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                        \t팀관리\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                    </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t                 </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t             </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div> -->\r\n");
      out.write("\t          \t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("<!-- \t\t<div class=\"modal\" id=\"manage\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("\t\t\t<div class=\"modal-dialog\">\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                     <div class=\"modal-header\">\r\n");
      out.write("                         <h4 class=\"modal-title\" align=\"center\">Manage Team</h4>\r\n");
      out.write("                     </div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("                        <form id=\"manage\">\r\n");
      out.write("                        \t팀관리\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                 </div>\r\n");
      out.write("             </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t -->\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /WEB-INF/view/member/MemberInformation.jsp(7,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("root");
    // /WEB-INF/view/member/MemberInformation.jsp(7,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f1.setParent(null);
    // /WEB-INF/view/member/MemberInformation.jsp(226,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f1.setVar("Username");
    // /WEB-INF/view/member/MemberInformation.jsp(226,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ sessionScope._MEMBER_.name }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
    if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f2.setParent(null);
    // /WEB-INF/view/member/MemberInformation.jsp(227,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f2.setVar("Useremail");
    // /WEB-INF/view/member/MemberInformation.jsp(227,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ sessionScope._MEMBER_.email }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fset_005f2 = _jspx_th_c_005fset_005f2.doStartTag();
    if (_jspx_th_c_005fset_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f3 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f3.setParent(null);
    // /WEB-INF/view/member/MemberInformation.jsp(228,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f3.setVar("picName");
    // /WEB-INF/view/member/MemberInformation.jsp(228,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f3.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ sessionScope._MEMBER_.pic_name }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fset_005f3 = _jspx_th_c_005fset_005f3.doStartTag();
    if (_jspx_th_c_005fset_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f3);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f4 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f4.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f4.setParent(null);
    // /WEB-INF/view/member/MemberInformation.jsp(229,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f4.setVar("picPath");
    // /WEB-INF/view/member/MemberInformation.jsp(229,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f4.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ sessionScope._MEMBER_.pic_path }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fset_005f4 = _jspx_th_c_005fset_005f4.doStartTag();
    if (_jspx_th_c_005fset_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f4);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f5 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f5.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f5.setParent(null);
    // /WEB-INF/view/member/MemberInformation.jsp(230,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f5.setVar("root");
    // /WEB-INF/view/member/MemberInformation.jsp(230,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f5.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fset_005f5 = _jspx_th_c_005fset_005f5.doStartTag();
    if (_jspx_th_c_005fset_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f5);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/view/member/MemberInformation.jsp(283,33) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ picName  ne null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                                \t\t<img src=\"/callImageServlet\" class=\"img-responsive\" alt=\"\">\r\n");
        out.write("                                \t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /WEB-INF/view/member/MemberInformation.jsp(286,36) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ picName  eq null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                                    \t<img src=\"resource/img/notifications.png\" class=\"img-responsive\">\r\n");
        out.write("                                    ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /WEB-INF/view/member/MemberInformation.jsp(374,14) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ allTeams }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    // /WEB-INF/view/member/MemberInformation.jsp(374,14) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("teams");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"listview lv-user m-t-20\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"lv-item media\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t    <div class=\"lv-avatar bgm-red pull-left\">t</div>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t    <div class=\"media-body\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t        <div class=\"lv-title\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ teams.teamName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("  ( Member Count : ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ teams.memCount }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" )</div>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t        <div class=\"lv-small\">Leader ID : ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ teams.leaderEmail }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</div>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t    </div>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t     </div>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }
}
